# To operate 'ln -s ~/dotfiles/zsh/zshrc ~/.zshrc'

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  asdf # installer like brew but dumber
  autojump
  git
  kubectl\
  zsh-autosuggestions # autosuggestions is the bomb dot com!!!
  zsh-syntax-highlighting # this lets you color code it allllllllll.... installed with git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
)

# Autocomplete color
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=100"

ZSH_THEME="robbyrussell"
# ZSH_THEME="Gnzh"

source $ZSH/oh-my-zsh.sh

source ~/dotfiles/zsh/config.zsh # IDK if this works but it seems like what i lifted from https://scriptingosx.com/2019/06/moving-to-zsh-part-3-shell-options/

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

########## End ZSH

# aliases
# alias ctx=kubectx
alias gbr='gh pr view -w'
alias dbc='osascript ~/dotfiles/osascripts/browser chrome'
alias dbf='osascript ~/dotfiles/osascripts/browser firefox'
alias dot='j dotfiles'
alias gpull='git pull'
alias k=kubectl
alias tf=terraform
alias zrf='source ~/.zshrc && echo "refreshed zsh profile!"'
alias zshrc='code ~/dotfiles; code ~/.zshrc && cd ~/dotfiles/zsh'
alias gitrc='code ~/dotfiles; code ~/.gitconfig && cd ~/dotfiles/git'
alias gbrowse='gh browse'
alias tflocal='bash <(curl https://nexus.opstempus.com/repository/devops/production/scripts/tflocal)'
alias be='bundle exec'

# env vars
export AWS_PAGER="" # Disable weird aws cli thing
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
export TFENV_ARCH=amd64 # to spoof being on an amd machine
export PATH="$HOME/bin:$PATH" # adds ~/bin to the paths
export PATH="$HOME/dotfiles/bash:$PATH" # adds ~/dotfiles/bash to the paths
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH" # Adds ~/.krew to the paths
export KUBE_EDITOR="code -w" # kubernetes editor vim
export PATH=$HOME/go/bin:$PATH
export PATH=$HOME/.asdf/shims:$PATH
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"


# Libsonnet detection for autoform modules
mods=~/tempus/iac/autoform-modules
export mods=$mods
export JSONNET_PATH=$mods/jsonnet/concourse-libsonnet:$mods/jsonnet/tempus-libsonnet # this gets out of date so im just dropping it

eval "$(/opt/homebrew/bin/brew shellenv)"

# If set, this option causes globs which do not match a file to result in an error without running the command. If unset, the command is run with the un-expanded glob. prevents "no match found" error in tf
unsetopt NOMATCH

# gcloud SDK Autocompletions
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

# argo rollouts
# source <(kubectl-argo-rollouts completion zsh)


# prunes local branches git
# will not delete anything by itself instead do
# git-prune-local | xargs git branch -d
git-prune-local() {
  git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}'
}

# up moves you up a directory
up() {
  local op=print
  [[ -t 1 ]] && op=cd
  case "$1" in
    '') up 1;;
    -*|+*) $op ~$1;;
    <->) $op $(printf '../%.0s' {1..$1});;
    *) local -a seg; seg=(${(s:/:)PWD%/*})
        local n=${(j:/:)seg[1,(I)$1*]}
        if [[ -n $n ]]; then
        $op /$n
        else
        print -u2 up: could not find prefix $1 in $PWD
        return 1
        fi
  esac
}

# drop lockfile and terraform dirs
def tfcleanlocal() {
    find . -type f -name ".terraform.lock.hcl" -delete
    find . -type d -name ".terraform" -prune -exec rm -rf {} \;
    find . -type f -name ".identity" -delete
}

# enable direnv globally
eval "$(direnv hook zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source <(kubectl completion zsh)
source <(fly completion --shell bash)

# Enable mcfly CMD+R Rust thingy globally
eval "$(mcfly init zsh)"
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
